tasks:
  - name: Thresh
    init: pip install -r requirements.txt && pip install -e '.[dev]'
    command: python -m app.main

ports:
  - port: 8000
    onOpen: open-browser
    name: Thresh
    visibility: private
